version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: conectacg_db_dev
    environment:
      POSTGRES_USER: ppedroxnx
      POSTGRES_PASSWORD: 130792
      POSTGRES_DB: conectacg
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: conectacg_redis_dev
    ports:
      - "6379:6379"

volumes:
  postgres_dev_data: